<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>embedded</DebugType>
    <AssemblyName>CS2-ResEdit</AssemblyName>
    <RootNamespace>Softhe.CS2ResEdit.Editor</RootNamespace>
    <ApplicationIcon>..\..\assets\cs2-resedit.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CS2ResEdit.Core\CS2ResEdit.Core.csproj" />
  </ItemGroup>
</Project>
